const fs = require('fs-extra');
const path = require('path');

/**
 * Modifier - The "Muscles" of the Nexus Engine.
 * Handles atomic file operations requested by the Orchestrator.
 */
class Modifier {
    constructor(rootPath) {
        this.rootPath = rootPath;
    }

    /**
     * Apply an action to the file system
     * @param {Object} action - { type, target, content, replacement }
     */
    async apply(action) {
        if (!action || !action.type) return false;

        const targetPath = path.resolve(this.rootPath, action.target);
        
        // Security Guard: Prevent writing outside root
        if (!targetPath.startsWith(this.rootPath)) {
            throw new Error(`Security Violation: Attempted to write outside project root: ${action.target}`);
        }

        switch (action.type) {
            case 'FILE_CREATE':
                return await this.fileCreate(targetPath, action.content);
            case 'FILE_APPEND':
                return await this.fileAppend(targetPath, action.content);
            case 'FILE_REPLACE':
                return await this.fileReplace(targetPath, action.targetContent, action.replacementContent);
            case 'BATCH_REPLACE':
                return await this.batchReplace(targetPath, action.replacements);
            case 'RESOLVE_OPTIONS':
                return await this.resolveOptions(targetPath, action.choice);
            default:
                throw new Error(`Unknown action type: ${action.type}`);
        }
    }

    /**
     * Resolve a Multi-Option block into a single chosen path.
     * @param {string} filePath 
     * @param {string} choice - 'A' or 'B'
     */
    async resolveOptions(filePath, choice = 'A') {
        if (!(await fs.pathExists(filePath))) throw new Error(`File not found: ${filePath}`);
        
        let content = await fs.readFile(filePath, 'utf8');
        
        // Regex to capture the Multi-Option blocks and the whole collision section
        const regexA = /#### Opsi A: [^\n]*\n([\s\S]*?)(?=\n---)/;
        const regexB = /#### Opsi B: [^\n]*\n([\s\S]*?)(?=\n---)/;
        
        // This matches the entire generated collision block including the footer
        const finalRegex = /### 🧩 Pilihan Opsi Tak Terbatas:[\s\S]*?\*(?:Generated by Nexus Engine|Merged by Nexus Distiller).*?\*/s;

        const matchA = content.match(regexA);
        const matchB = content.match(regexB);
        
        if (!matchA || !matchB) {
             throw new Error(`Multi-Option block not found or malformed in ${filePath}`);
        }

        const selectedContent = (choice.toUpperCase() === 'A') ? matchA[1].trim() : matchB[1].trim();
        
        if (content.match(finalRegex)) {
            const newContent = content.replace(finalRegex, selectedContent);
            await fs.writeFile(filePath, newContent.trim());
            return true;
        }
        
        return false;
    }

    /**
     * Perform multiple replacements in a single file
     * @param {string} filePath 
     * @param {Array} replacements - Array of { target, replacement }
     */
    async batchReplace(filePath, replacements) {
        if (!(await fs.pathExists(filePath))) throw new Error(`File not found: ${filePath}`);
        
        let content = await fs.readFile(filePath, 'utf8');
        let modified = false;

        for (const r of replacements) {
            if (content.includes(r.target)) {
                content = content.replace(new RegExp(this.escapeRegExp(r.target), 'g'), r.replacement);
                modified = true;
            }
        }

        if (modified) {
            await fs.writeFile(filePath, content);
            return true;
        }
        return false;
    }

    escapeRegExp(string) {
        return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    }

    async fileCreate(filePath, content) {
        await fs.ensureDir(path.dirname(filePath));
        await fs.writeFile(filePath, content || '');
        return true;
    }

    async fileAppend(filePath, content) {
        if (await fs.pathExists(filePath)) {
            await fs.appendFile(filePath, `\n${content}`);
            return true;
        }
        return await this.fileCreate(filePath, content);
    }

    async fileReplace(filePath, targetContent, replacementContent) {
        if (await fs.pathExists(filePath)) {
            let content = await fs.readFile(filePath, 'utf8');
            if (content.includes(targetContent)) {
                const newContent = content.replace(targetContent, replacementContent);
                await fs.writeFile(filePath, newContent);
                return true;
            }
            throw new Error(`Target content not found in file: ${filePath}`);
        }
        throw new Error(`File not found: ${filePath}`);
    }
}

module.exports = Modifier;
